name: Lint Code

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy

    - name: Run black
      run: black --check ./linked_list.py && black --check ./queue.py && black --check ./stack.py 

    - name: Run isort
      run: isort --check-only ./linked_list.py && isort --check-only ./queue.py && isort --check-only ./stack.py

    - name: Run flake8
      run: flake8 ./linked_list.py && flake8 ./queue.py && flake8 ./stack.py

    - name: Run mypy 
      run: mypy ./linked_list.py && mypy ./queue.py && mypy ./stack.py
