name: Lint Code

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy

    - name: Run black
      run: black --check ./"5 homework"/5_homework.py

    - name: Run isort
      run: isort --check-only ./"5 homework"/5_homework.py

    - name: Run flake8
      run: flake8 ./"5 homework"/5_homework.py

    - name: Run mypy 
      run: mypy ./"5 homework"/5_homework.py
